.sync/PackageCi.yml: Fix Version.njk import path (#546)
Version.njk is located two levels above the PackageCi.yml.

.sync/
├── Version.njk *
└── workflows/
    └── leaf/
        └── PackageCi.yml *

This resolves an error during file sync after commit ec8aaf3:

> Repo File Sync
(mu_devops/.sync/workflows/leaf/PackageCi.yml)
  Template render error: (mu_devops/.sync/workflows/leaf/PackageCi.yml)
  Error: template not found: mu_devops/.sync/workflows/Version.njk

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>